#!/bin/sh

# DEFINE INPUT PARAMETER --------------------------------------------------------------------------------------------- #

TARGET_MAJOR_VERSION=$1
TARGET_MINOR_VERSION=$2
PATH_TO_PROJECT=$3

## validate input parameters
if [ $# -ne 3 ]
  then
    echo "Invalid nr of arguments supplied; Expected <TARGET_MAJOR_VERSION> <TARGET_MINOR_VERSION> <PATH_TO_PROJECT>"
    exit 255
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
# END DEFINE INPUT PARAMETER ------------------------------------------------------------------------------------- END #





# ==> MAIN LOGIC <== #
java -jar "$SCRIPT_DIR/bin/setpomversion.jar" "$TARGET_MAJOR_VERSION" "$TARGET_MINOR_VERSION" "$PATH_TO_PROJECT"
