#!/bin/sh
# DEFINE INPUT PARAMETER --------------------------------------------------------------------------------------------- #

TARGET_MAJOR_VERSION=$1
TARGET_MINOR_VERSION=$2

## validate input parameters
if [ $# -ne 2 ]; then
  echo "Invalid nr of arguments supplied; Expected <TARGET_MAJOR_VERSION> <TARGET_MINOR_VERSION>"
  exit 255
fi

## validate if we are calling from correct directory
TASK_DIRECTORY=$(pwd)
if test -d "$TASK_DIRECTORY/lib"; then
  echo "Calling from correct directory"
  # Add lib to path
  export PATH=$PATH:$TASK_DIRECTORY:$TASK_DIRECTORY/lib
else
  echo "You didnt call from tasks directory!"
  exit 255
fi

# END DEFINE INPUT PARAMETER ------------------------------------------------------------------------------------- END #





# ==> MAIN LOGIC <== #
#task-ssc-licensegenerator
task-precheck
if [ $? -eq 0 ]; then
  task-prepare-release "$TARGET_MAJOR_VERSION" "$TARGET_MINOR_VERSION"
  task-commit-release "$TARGET_MAJOR_VERSION" "$TARGET_MINOR_VERSION"
else
  echo "At least one of the project folders does not have a clean git state!"
fi
