#!/bin/sh

# DEFINE INPUT PARAMETER --------------------------------------------------------------------------------------------- #

TARGET_MAJOR_VERSION=$1
TARGET_MINOR_VERSION=$2

## validate input parameters
if [ $# -ne 2 ]; then
  echo "Invalid nr of arguments supplied; Expected <TARGET_MAJOR_VERSION> <TARGET_MINOR_VERSION>"
  exit 255
fi

## validate if we are calling from correct directory
TASK_DIRECTORY=$(pwd)
if test -d "$TASK_DIRECTORY/lib"; then
  echo "Calling from correct directory"
  # Add lib to path
  export PATH=$PATH:$TASK_DIRECTORY:$TASK_DIRECTORY/lib
else
  echo "You didnt call from tasks directory!"
  exit 255
fi

# END DEFINE INPUT PARAMETER ------------------------------------------------------------------------------------- END #





# ==> MAIN LOGIC <== #
echo "Prepare Release ..."
cd .. # Change working dir into project
git checkout -b release/"$TARGET_MAJOR_VERSION"."$TARGET_MINOR_VERSION".x     # Create and checkout release/<MAJOR>.MINOR>.X branch
setpomversion "$TARGET_MAJOR_VERSION" "$TARGET_MINOR_VERSION" "$TASK_DIRECTORY/$_dir"
