#!/bin/sh

# variables
MARIADB_NAME="springboottemplate-mariadb"
MARIADB_PORT="8033"
MARIADB_DATA_DIRECTORY="db-datadir"
MARIADB_USER="templateUser"
MARIADB_PASSWORD="templatePwd"
MARIADB_ROOT_PASSWORD="templateRootPwd"
PROJECT_FOLDER=$(pwd)

docker pull mariadb

DOCKER_DBCONTAINER_FILTER_STRIMG=$(docker ps --filter name=$MARIADB_NAME)
echo $DOCKER_DBCONTAINER_FILTER_STRIMG
if [[ $DOCKER_DBCONTAINER_FILTER_STRIMG == *"$MARIADB_NAME"* ]]; then
  echo "Container $MARIADB_NAME was found!"
  # start if exists
  docker start $MARIADB_NAME
else
  echo "Container $MARIADB_NAME is missing!"
  # create container:
  mkdir -p "../$MARIADB_DATA_DIRECTORY"
  docker run -p $MARIADB_PORT:3306 -v "$PROJECT_FOLDER"/../$MARIADB_DATA_DIRECTORY:/var/lib/mysql --detach --name $MARIADB_NAME --env MARIADB_USER=$MARIADB_USER --env MARIADB_PASSWORD=$MARIADB_PASSWORD --env MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD mariadb:latest
  docker start $MARIADB_NAME
fi

# wait until db is startet and initialized
sleep 10

# run mariadb-docker-local cli, connected to running
docker run --name $MARIADB_NAME-cli -it --rm mariadb mysql -hhost.docker.internal --port=$MARIADB_PORT -uroot -p$MARIADB_ROOT_PASSWORD

# EXECUTE manually ...
#CREATE DATABASE template_db;
